language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"
before_script:
  - npm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test:cover
after_script:
  - ./cc-test-reporter format-coverage -t lcov -o coverage/lcov.info  # Format frontend coverage
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage  -i coverage/lcov.info; fi

